### ISSUE TITLE
It would be nice to have mobile functionality 

### ISSUE THREAD

**Issue by zaidsidd360** [bony2023/react-terminal#234]
Was it a choice to not make it for mobile? Or does it break something if used on a mobile so mobile usage was let go? I'm really curious. I made a project using react-terminal and later found out that it wouldn't function as expected on my phone. So I had to scrap all the responsiveness for that project and instead just asked the user to please open the app on a desktop. Anyway, amazing work @bony2023 and everyone involved!

**Comment by bony2023** [comment]
@zaidsidd360 Thanks for creating issue for it. The mobile support used to work before but suddenly it stopped some time back. I have yet to debug the underlying issue (browser update / functionality deprecated etc) but I think it will be tricky as the terminal not using native `<input>` tag to receive inputs from keyboard.

**Comment by raaaahman** [comment]
>  I think it will be tricky as the terminal not using native `<input>` tag to receive inputs from keyboard.

I'm curious about that choice, why not use an input element?

PrimeReact's Terminal seems to use one fine: https://github.com/primefaces/primereact/blob/b21aacf6efe50642e9f41d8f7c065ddf6683d6f9/components/lib/terminal/Terminal.js#L130

**Comment by 0NotApplicable0** [comment]
An input element is using the native `<input>`?

```
<input
        type="text"
        autoComplete="off"
        autoCorrect="off"
        autoCapitalize="off"
        spellCheck="false"
        value={editorInput}
        onChange={(event) => setEditorInput(event.target.value)}
        ref={mobileInputRef}
      />
```

Anyway, I figured out the issue and its a two fold.
The first issue is that react-device-detect seems to not be correctly figuring out if a device is one mobile or not. Downgrading to v2.1.2 seems to fix that issue.
The second issue is that browsers (and mobile devices) in general don't like allowing events (including .focus()) to be called automatically and they should be called within some sort of onClick event instead of in useEffect.

I will offer up a PR to fix this.
